# 自动生成的书签配置文件
# 由bookmark-processor.js生成于 2025-06-17T11:48:38.967Z
# 若要更新，请将新的书签HTML文件放入bookmarks/目录
# 此文件使用模块化配置格式，位于config/user/pages/目录下

title: 我的书签
subtitle: 从浏览器导入的书签收藏
categories:
  - name: 部署
    icon: fas fa-folder
    sites:
      - name: vercel
        url: https://vercel.com/
        icon: fas fa-link
        description: ""
      - name: neon
        url: https://console.neon.tech/
        icon: fas fa-link
        description: ""
      - name: clerk
        url: https://dashboard.clerk.com/
        icon: fas fa-link
        description: ""
      - name: Koyeb
        url: https://app.koyeb.com/
        icon: fas fa-link
        description: ""
  - name: 项目
    icon: fas fa-folder
    sites:
      - name: CloudPaste - 安全分享您的内容
        url: https://file.456147.xyz/admin
        icon: fas fa-link
        description: ""
      - name: Temp Email
        url: https://email.456147.xyz/
        icon: fas fa-link
        description: ""
      - name: LobeChat：个人 AI 效能工具，给自己一个更聪明的大脑
        url: https://lobe.zuidiao.de/
        icon: fas fa-link
        description: ""
      - name: Deep Research
        url: https://paper.zuidiao.de/
        icon: fas fa-link
        description: ""
      - name: uni-api-config-generator
        url: http://uicfg.zuidiao.de/
        icon: fas fa-link
        description: ""
  - name: 实用
    icon: fas fa-folder
    sites:
      - name: uni-api 配置生成器
        url: https://uni-api-config-generator.vercel.app/
        icon: fas fa-link
        description: ""
  - name: 其他书签
    icon: fas fa-folder
    sites:
      - name: 爱妹子
        url: https://xx.knit.bid/
        icon: fas fa-link
        description: ""
      - name: AI Féng Hé Guài(缝合怪)(bsdsma.com)_Java代码生成器，远程1对1服务
        url: https://bsdsma.com/
        icon: fas fa-link
        description: ""
      - name: 子夜星网站 · Midnight Star ·
        url: http://www.ziyexing.com/
        icon: fas fa-link
        description: ""
      - name: 授粉.AI
        url: https://pollinations.ai/
        icon: fas fa-link
        description: ""
      - name: 美国地址 • 包裹转运 • Planet Express
        url: https://planetexpress.com/?ref=329577
        icon: fas fa-link
        description: ""
      - name: 打字鸭 - 专业的在线打字练习平台
        url: https://daziya.com/lesson/?courseId=8a269301536307f71deaab723e12c84d&amp;lessonId=743bd2b8f6299f509ba58e268936e43b
        icon: fas fa-link
        description: ""
      - name: 比较所有顶级域名的价格 | 顶级域名列表
        url: https://zh-hans.tld-list.com/
        icon: fas fa-link
        description: ""
      - name: 哪里注册de域名最便宜 - 第1页 - 哪煮米
        url: https://www.nazhumi.com/domain/de/1
        icon: fas fa-link
        description: ""
      - name: 无损控 - 无损音乐下载FLAC,WAV,APE,MP3格式高品质歌曲免费下载网站
        url: https://wusunk.com/
        icon: fas fa-link
        description: ""
      - name: 汽车票查询,汽车票网上订购,汽车票-新途云汽车票
        url: https://m.xintuyun.cn/html/index.html?ttsid=85&amp;code=09152m100wPIqS1wzL100ZUeC4052m1G#/
        icon: fas fa-link
        description: ""
      - name: Experiments
        url: chrome://flags/#fluent-overlay-scrollbars
        icon: fas fa-link
        description: ""
      - name: 哪里注册de域名最便宜 - 第1页 - 哪煮米
        url: https://www.nazhumi.com/domain/de/1
        icon: fas fa-link
        description: ""
      - name: flowith 2.0 - Your AI Creation Workspace, with Knowledge
        url: https://flowith.io/blank
        icon: fas fa-link
        description: ""
      - name: 自由钢琴 - AutoPiano | 在线钢琴，键盘钢琴，模拟钢琴，多种乐器选择，好听又好玩
        url: https://www.autopiano.cn/
        icon: fas fa-link
        description: ""
      - name: 已删除域名 | 您现在可以购买的可用域名！
        url: https://www.expireddomains.net/deleted-domains/
        icon: fas fa-link
        description: ""
      - name: englishdaily.ai
        url: https://englishdaily.ai/
        icon: fas fa-link
        description: ""
  - name: 移动设备书签
    icon: fas fa-folder
    sites:
      - name: Interesting open-source community - HelloGitHub
        url: https://hellogithub.com/en
        icon: fab fa-github
        description: ""
      - name: hrpzcf/AwesomePyKit
        url: https://gitee.com/hrpzcf/AwesomePyKit
        icon: fas fa-link
        description: ""
